os: osx
language: objective-c
sudo: required
dist: trusty
osx_image: xcode8.3
before_install:
 before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'
  - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
xcode_workspace: PodCatcher/PodCatcher.xcworkspace
xcode_scheme: PodCatcherTests
script: rvm get stable  && xcodebuild test -workspace PodCatcher/PodCatcher.xcworkspace -destination "platform=IOS Simulator,name=iPhone 6s" -scheme PodCatcher build && xcodebuild -workspace PodCatcher/PodCatcher.xcworkspace -destination "platform=IOS Simulator,name=iPhone 6s" -scheme PodCatcherTests 


