language: objective-c
sudo: required
dist: trusty
osx_image: xcode8.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - XCODEPROJ=PodCatcher.xcodeproj.xcodeproj
script:
  - xcodebuild -version
  - xcodebuild -workspace PodCatcher.xcworkspace -scheme PodCatcher -configuration Debug  
clean build