os: osx
language: objective-c
sudo: required
dist: trusty
osx_image: xcode8.3
matrix:
  - DESTINATION="OS=10.3.1,name=iPhone SE" SCHEME="$IOS_FRAMEWORK_SCHEME"
before_install:
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6s (10.3” | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
  - cd PodCatcher
  - gem install cocoapods --pre
  - pod repo update
  - pod install
  - cd ..
  - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
xcode_workspace: PodCatcher/PodCatcher.xcworkspace
xcode_scheme: PodCatcherTests
script: rvm get stable  && xcodebuild test -workspace PodCatcher/PodCatcher.xcworkspace -destination "platform=IOS Simulator,name=iPhone 6s" -scheme PodCatcher build && xcodebuild -workspace PodCatcher/PodCatcher.xcworkspace -destination "platform=IOS Simulator,name=iPhone 6s" -scheme PodCatcherTests && xcodebuild -workspace PodCatcher/PodCatcher.xcworkspace -destination "platform=IOS Simulator,name=iPhone 6s" -scheme PodCatcherUITests 


