os:
- linux
- osx
language: objective-c
sudo: required
osx_image: xcode8.3
install:
- curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
- . ~/.swiftenv/init
- swift build
- xcodebuild -scheme PodCatcher -workspace PodCatcher.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.3’ build test